# Generated by Django 2.2.10 on 2020-12-13 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorting',
            name='destination',
            field=models.URLField(help_text='The destination URL to be redirected', null=True, validators=[django.core.validators.URLValidator]),
        ),
    ]
